-- DATABASE LEVEL -

CREATE DATABASE COMPANY_DB;

SHOW DATABASES;

CREATE DATABASE COMPANY_DB;

CREATE DATABASE IF NOT EXISTS COMPANY_DB;

CREATE DATABASE HOSPITAL_DB;

CREATE DATABASE LIBRARY_DB;

CREATE DATABASE SCHOOL_DB;

DROP DATABASE LIBRARY_DB;

DROP DATABASE LIBRARY_DB;

DROP DATABASE IF EXISTS library_db;

DROP DATABASE HOSPITAL_DB;

DROP DATABASE SCHOOL_DB;

CREATE DATABASE IF NOT EXISTS COLLEGE_DB;

USE COLLEGE_DB;

SHOW DATABASES;

DROP DATABASE IF EXISTS COLLEGE_DB;

DROP DATABASE COLLEGE_DB;

-- ------------------------------------------- --
-- TABLES LEVEL --
-- 1 --

CREATE DATABASE IF NOT EXISTS sql_practice_db;

USE sql_practice_db;

CREATE TABLE EMPLOYEES(
	EMPLOYEE_ID INT,
    NAME VARCHAR(50),
    AGE TINYINT,
    SALARY DECIMAL(10,2),
    JOINING_DATE DATE
);

SHOW TABLES;

DESC EMPLOYEES;

SHOW CREATE TABLE EMPLOYEES;

-- 2 --

CREATE TABLE STUDENT(
	STUDENT_ID INT,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    DOB DATE,
    MOBILE VARCHAR(20),
    EMAIL VARCHAR(50),
    CGPA FLOAT,
    PASSING_YEAR VARCHAR(5)
);

DESC STUDENT;

DROP TABLE STUDENT;

-- DROPPED FEW DATATYPES WERE WRONG --

CREATE TABLE students(
    student_id INT,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    dob DATE,
    mobile VARCHAR(15),
    email VARCHAR(255),
    cgpa DECIMAL(3,2),
    passing_year YEAR
);

-- 3 --

CREATE TABLE PRODUCT (
	PRODUCT_ID INT,
	PRODUCT_NAME VARCHAR(50),
	BRAND VARCHAR(50),
	CATEGORY VARCHAR(50),
	PRICE DECIMAL(10,2),
	STOCK_QUANTITY INT,
	MANUFACTURING_DATE DATE,
	EXPIRY_DATE DATE,
	DESCRIPTION TEXT
);

-- EVERYTHING WAS CORRECT IN 3RD QUESTION --

--  ALTER TABLE --

-- 1 --

ALTER TABLE EMPLOYEES
ADD COLUMN EMAIL VARCHAR(100);

DESC EMPLOYEES;

-- 2 --

ALTER TABLE EMPLOYEES
ADD COLUMN PHONE VARCHAR(20),
ADD COLUMN DESCRIPTION TEXT;

DESC EMPLOYEES;

-- 3 --
-- Increase the size of --

ALTER TABLE EMPLOYEES
MODIFY COLUMN NAME VARCHAR(100);

DESC EMPLOYEES;

-- 4 --
-- Rename --

ALTER TABLE EMPLOYEES
RENAME COLUMN NAME TO EMPLOYEE_NAME;

DESC EMPLOYEES;

-- 5 --
-- Rename MONTHLY SALARY AND DATATYPE TO DECIMAL(12,2) --

ALTER TABLE EMPLOYEES
CHANGE SALARY MONTHLY_SALARY DECIMAL(12,2);

DESC EMPLOYEES;

-- 6 --
-- DELETE PHONE --

ALTER TABLE EMPLOYEES
DROP COLUMN PHONE;

DESC EMPLOYEES;

-- 7 --
-- RENAME TABLE --

ALTER TABLE EMPLOYEES
RENAME TO EMPLOYEE_MASTER;

DESC EMPLOYEE_MASTER;

-- -------------------- --
-- TRUNCATE TABLE --

-- 1 --

CREATE TABLE TEMP_STUDENTS (
	STUDENT_ID INT,
	STUDENT_NAME VARCHAR(50)
);

-- 2 --

TRUNCATE TABLE TEMP_STUDENTS;

-- 3 --

DESC TEMP_STUDENTS;

-- 4 --
-- TRYING TO INSERT VALUES STILL NOT PRACTICED THIS --

INSERT INTO TEMP_STUDENTS (STUDENT_ID, STUDENT_NAME)
VALUES (001, "MCB");

DESC TEMP_STUDENTS;

SELECT * FROM TEMP_STUDENTS;

TRUNCATE TEMP_STUDENTS;

SELECT * FROM TEMP_STUDENTS;

-- -------------- --

-- DROP TABLE --
-- 1 --

CREATE TABLE TEST_TABLE (
	ID INT,
    NAME VARCHAR(50)
);

-- 2 --
SHOW TABLES;

-- 3 --

DROP TABLE TEST_TABLE;

-- 4 --

SHOW TABLES;

-- 5 --
DROP TABLE test_table;

-- 6 --
DROP TABLE IF EXISTS test_table;